export const FETCH_PATROLS = 'FETCH_PATROLS';
export const FETCH_HOME_PATROLS = 'FETCH_HOME_PATROLS';

export const SIDEDRAWER_OPEN = 'SIDEDRAWER_OPEN';

export const SELECTED_MARKER = 'SELECTED_MARKER';